### ISSUE TITLE
cannot run notebook: pandas missing

### ISSUE THREAD

**Issue by egonw** [OpenRiskNet/notebooks#2]
@thomasexner, I cannot run your notebook on https://jupyterhub-jupyter.prod.openrisknet.org/: it says pandas is not available:

![image](https://user-images.githubusercontent.com/26721/43916610-581ffbfc-9c0e-11e8-8d0c-4611da9f0c85.png)

Got suggestions for what I should do?

**Comment by egonw** [comment]
I added the following line, which seems to help:

```python
!pip install pandas
```

**Comment by egonw** [comment]
it seems `seaborn` also needs installation...

**Comment by thomasexner** [comment]
New version of notebook checks if all needed libraries are installed and executes the needed pip commands for all missing libraries.
