### ISSUE TITLE
Rscript missing in Jupyter notebooks

### ISSUE THREAD

**Issue by lucfar** [OpenRiskNet/notebooks#5]
From the error below I bilieve the R is not installed in OpenRiskNet jupyter, so we cannot run such scripts yet.
![capture](https://user-images.githubusercontent.com/13434317/52046871-157e9100-2548-11e9-82b1-7b98545292dd.PNG)

**Comment by tdudgeon** [comment]
@lucfar 
this repo is for actual notebooks, whilst this issue is really about the Jupyter infrastructure so should be raised in the home repo: https://github.com/OpenRiskNet/home/issues
I'm going to close this issue here. Could you raise it in that repo and tag it with the jupyterhub label.
